x-neo4j_container: &neo4j_container
  image: neo4j:3.5
  ports:
    - "7474:7474"
    - "7687:7687"
  environment:
    NEO4J_AUTH: none

version: '3.6'
services: 
    neo4j_development: 
        <<: *neo4j_container
        container_name: neo4j_development

networks:
    default:
          