# start from golang image based on alpine-3.8
FROM golang:1.14-alpine3.11 AS dev-build

# add our cgo dependencies
RUN apk add --update --no-cache ca-certificates cmake make g++ openssl-dev openssl-libs-static git curl pkgconfig

# clone seabolt-1.7 source code
RUN git clone -b 1.7 https://github.com/neo4j-drivers/seabolt.git /seabolt

# invoke cmake build and install artifacts - default location is /usr/local
WORKDIR /seabolt/build

# CMAKE_INSTALL_LIBDIR=lib is a hack where we override default lib64 to lib to workaround a defect
# in our generated pkg-config file 
RUN cmake -D CMAKE_BUILD_TYPE=Release -D CMAKE_INSTALL_LIBDIR=lib .. && cmake --build . --target install

WORKDIR /go/src/app
ADD . /go/src/app

# Install Sentinel
RUN go get -d -v ./...
RUN go install -v ./...
RUN make swagger

CMD ["sh", "-c", "$GOPATH/bin/sentinel"]
