version: '3.6'
services: 
    api:
        build: .
        container_name: api
        network_mode: "bridge"
        depends_on:
            - neo4j_development
        ports:
            - "8080:8080"
        links:
            - neo4j_development:neo4j_development
        environment: 
            DB_URI: bolt://neo4j_development:7687
            HOST: localhost
            PORT: 8080
            USERNAME: ""
            PASSWORD: ""
            
    neo4j_development: 
        container_name: neo4j_development
        network_mode: "bridge"
        image: neo4j:3.5
        ports:
            - "7474:7474"
            - "7687:7687"
        environment:
            NEO4J_AUTH: none