name: Sentinel Community Deployment

on:
  push:
    branches: [master]

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v2
      with:
            token: ${{ secrets.PAT }} 

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
    - run: |
            cd infrastructure/dev
            terraform init
            terraform plan
            terraform apply -auto-approve
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    
    


      