on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
        matrix:
            go-version: [1.14.x]
    runs-on: ubuntu-latest
    steps:
        - name: Install Go
          uses: actions/setup-go@v2
          with:
              go-version: ${{ matrix.go-version }}
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Install seabolt Dependencies
          run: sudo apt-get install -y libssl1.0.0 

        - name: Fetch latest package
          run: wget https://github.com/neo4j-drivers/seabolt/releases/download/v1.7.4/seabolt-1.7.4-Linux-ubuntu-$(lsb_release -rs).deb

        - name: Unzip seabolt dependencies
          run: sudo dpkg -i seabolt-1.7.4-Linux-ubuntu-$(lsb_release -rs).deb

        - name: Clone seabolt repository
          run: sudo git clone -b 1.7 https://github.com/neo4j-drivers/seabolt.git /seabolt

        - name: Generate coverage
          run: ./cover.sh
