on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
        matrix:
            go-version: [1.13.x, 1.14.x]
    runs-on: ubuntu-latest
    steps:
        - name: Install Go
          uses: actions/setup-go@v2
          with:
              go-version: ${{ matrix.go-version }}
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Install ca-certificates
          run: sudo add-apt-repository ca-certificates
        - name: Bolt dependencies - Install
          run: sudo apt-get install ca-certificates
        - name: Clone seabolt repository
          run: sudo git clone -b 1.7 https://github.com/neo4j-drivers/seabolt.git /seabolt
        - name: Test
          run: go test ./...