name: Sentinel Deployment

on:
  push:
    branches: [staging]

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false

      - name: Terraform Apply
        id: terraform-apply
        run: |
          cd infrastructure/beanstalk
          terraform init
          terraform plan
          terraform apply -var 'username=${{ secrets.USERNAME }}' -var 'password=${{ secrets.PASSWORD }}' -var 'db_uri=${{ secrets.DB_URI }}' -var 'acm_certificate_arn=${{ secrets.ACM_CERTIFICATE_ARN }}' -var 'newrelicLicense=${{ secrets.NEW_RELIC_LICENSE }}' -auto-approve
          echo "WEBSITE_BUCKET=$(terraform output -json | jq -r .website_bucket_id.value)" >> $GITHUB_ENV
          echo "APPLICATION_NAME=$(terraform output -json | jq -r .application_name.value)" >> $GITHUB_ENV
          echo "ENVIRONMENT_NAME=$(terraform output -json | jq -r .environment_name.value)" >> $GITHUB_ENV

      - name: Generate deployment zip
        run: |
          cd apis/sentinel
          zip -r deploy.zip * -x "**.vscode**"

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v14
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ${{ env.APPLICATION_NAME }}
          environment_name: ${{ env.ENVIRONMENT_NAME }}
          version_label: ${{ github.sha }}
          region: us-east-1
          deployment_package: ./apis/sentinel/deploy.zip

      - name: Install Node
        uses: actions/setup-node@v2

      # - name: Install AWS CLI
      #   uses: chrislennon/action-aws-cli@v1.1

      - name: Build Website
        run: |
          cd dashboard
          npm install
          npm run build

      # - name: Deploy Website
      #   env:
      #     WEBSITE_BUCKET: ${{ env.WEBSITE_BUCKET }}
      #   run: |
      #     cd app
      #     aws s3 sync ./build/ s3://$WEBSITE_BUCKET
  
      - name: Deploy Website
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ env.WEBSITE_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-1'   # optional: defaults to us-east-1
          SOURCE_DIR: './dashboard/build'      # optional: defaults to entire repository